### ISSUE TITLE
Cannot sort from admin

### ISSUE THREAD

**Issue by DivaVocals** [bislewl/ajax_back_in_stock#1]
On the old Ceon one, you could sort by product, so when I was placing an order with a company I would just go into there and make sure I ordered what people were waiting on notifications for.  This one doesn’t sort at all (even though there is a link on the Products column).

**Comment by bislewl** [comment]
Currently this sorts not by product name but by product_id

**Comment by DivaVocals** [comment]
Not clear here.. is this fixed?? Because sorting doesn't work at all..

**Comment by bislewl** [comment]
It is not resolved as it sorts by products_id not by products model.

**Comment by DivaVocals** [comment]
Got it.. will look forward to seeing this incorporated
